version: '2'
name: picpay
services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    command: --sql-mode="NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
    environment:
      MYSQL_ROOT_PASSWORD: p1i2c3@pay
      MYSQL_DATABASE: picpay
      MYSQL_USER: picpay
      MYSQL_PASSWORD: p1i2c3@pay
    volumes:
      - ./data:/var/lib/mysql

    networks:
      - picpay

  node:
    container_name: node
    depends_on:
      - mysql
    build: 
      context: './'
      dockerfile: node.Dockerfile
    volumes: 
      - .:/api
    ports:
      - 8081:8081

networks:
  picpay:
    name: picpay
    driver: bridge
