version: '2'
name: picpay
services:
  mysql:
    image: mysql:8
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p1i2c3@pay
      MYSQL_DATABASE: picpay
      MYSQL_USER: picpay
      MYSQL_PASSWORD: p1i2c3@pay
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - picpay

  node:
    container_name: node
    depends_on:
      - mysql
    build: 
      context: './'
      dockerfile: node.Dockerfile
    environment:
      DB_HOST: mysql
    volumes: 
      - .:/usr/src/app
    ports:
      - 8081:8081
    networks:
      - picpay

networks:
  picpay:
    name: picpay
    driver: bridge
